### ISSUE TITLE
Is there any way to unsubscribe to "onChange" event

### ISSUE THREAD

**Issue by sqzbx** [apache/cordova-plugin-screen-orientation#44]
As the title... So I currently have the code

```
this.screenOrientation.onChange().subscribe(
  () => {
    // code
  }
);
```
This code gets subscribed on every time the page open and fires multiple times. I'm looking for a way for it to only trigger once. Any help will be appreciated... 💯

**Comment by sqzbx** [comment]
Found what I'm doing wrong...

Fixed doing something like...
```
const watch = this.screenOrientation.onChange().subscribe(
  () => {
    // code
  }
);

// onLeave
watch.unsubscribe();
```

**Comment by imposimato** [comment]
Hey sqzbx, I tried your suggestion but the problem persists.
Can you please give more insight on this issue?
Thanks!
